### ISSUE TITLE
Adapt matrix to be more RWD-friendly

### ISSUE THREAD

**Issue by krzysztofrewak** [krzysztofrewak/bjcp-ui#1]
Right now entire application looks the same on desktop and mobile devices. I think it would be great to enhace it somehow to be more mofortable for users with devices with smaller display resolutions.

I'm using Tailwind for frontend, so implementing responsiveness shouldn't be a big problem.

**Comment by cagomezr** [comment]
hey It  may require some custom css  would you like me to do it on the  file itself or separate also I may have to change  some of  your divisions  as main offenders are on your  header would that be ok?
